// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxrst-0okkKiRGnc1bOpYPMWfhVMiUjvo',
    appId: '1:95786185676:web:4d51b682bd9024d5e1e369',
    messagingSenderId: '95786185676',
    projectId: 'classnet-43f67',
    authDomain: 'classnet-43f67.firebaseapp.com',
    storageBucket: 'classnet-43f67.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4S2foEvgPf_bNYF0PYDj3hzfnNOeLOtI',
    appId: '1:95786185676:android:99d13db185141cefe1e369',
    messagingSenderId: '95786185676',
    projectId: 'classnet-43f67',
    storageBucket: 'classnet-43f67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcBADquwkaXPM0irxAdL8JjmkOaQGNaR0',
    appId: '1:95786185676:ios:6ffaaf28556175cfe1e369',
    messagingSenderId: '95786185676',
    projectId: 'classnet-43f67',
    storageBucket: 'classnet-43f67.appspot.com',
    iosBundleId: 'dev.agxpro.classnet',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcBADquwkaXPM0irxAdL8JjmkOaQGNaR0',
    appId: '1:95786185676:ios:702e026c7e4e8853e1e369',
    messagingSenderId: '95786185676',
    projectId: 'classnet-43f67',
    storageBucket: 'classnet-43f67.appspot.com',
    iosBundleId: 'dev.agxpro.classnet.RunnerTests',
  );
}
